apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novel.fullname" . }}
  labels:
    {{- include "novel.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      data:
        mongodb:
          uri: mongodb://root:Lgt_123@10.103.11.61:27017/novel
